-- Generated by scripts/generate-seed.mjs — do not hand-edit, regenerate instead.
-- Mirrors apps/web/src/app/core/state/seed/seed-state.ts exactly.

INSERT INTO simulations (id, world_pack_id, state_version, current_world_date, current_season, player_id, social_access_level, world_status_json, farm_json, finance_ledger_json, open_threads_json) VALUES (
  'sim_default', 'bridgerton', 1, '12. April 1813', 'spring', 'char_player_matthias', 1,
  '{"londonSeasonStatus":"gerade erst begonnen","socialMood":"neugierig, abwartend","region":"ländliches Umland Londons","weather":"leichter Nebel, mild"}', '{"id":"farm_hale","ownerId":"char_player_matthias","stats":{"landAcres":18,"annualRent":"£24 jährlich","livestock":"1 Kuh, 1 Zugpferd, 8 Hühner","supplies":"für den Winter knapp bemessen","workers":"Familie + gelegentliche Tagelöhner zur Ernte"},"calendar":[{"season":"spring","task":"Aussaat"},{"season":"summer","task":"Heuernte"},{"season":"autumn","task":"Getreideernte"},{"season":"winter","task":"Instandhaltung"}],"buildings":[{"id":"house","name":"Wohnhaus","condition":"worn"},{"id":"barn","name":"Scheune","condition":"worn"},{"id":"stable","name":"Stall","condition":"sound"},{"id":"fields","name":"Felder","condition":"sound"},{"id":"pasture","name":"Weiden","condition":"sound"},{"id":"garden","name":"Garten","condition":"worn"},{"id":"storage","name":"Lager","condition":"worn"},{"id":"drive","name":"Zufahrt","condition":"worn"}]}', '[{"id":"txn_1","date":"2. April 1813","description":"Saatgut","amount":-3.5},{"id":"txn_2","date":"5. April 1813","description":"Marktverkauf — Eier","amount":1.2},{"id":"txn_3","date":"9. April 1813","description":"Reparatur Zaun","amount":-0.8},{"id":"txn_4","date":"11. April 1813","description":"Pacht (Quartal)","amount":-6}]', '[]'
);

INSERT INTO characters (id, simulation_id, name, is_canon, is_player, location_id, appearance_json, visual_state_json, personality_json, goals_json, player_knowledge_json, gm_state_json) VALUES (
  'char_player_matthias', 'sim_default', 'Matthias Hale', 0, 1, 'loc_player_farm',
  '{"height":"mittelgroß","build":"drahtig-kräftig von der Feldarbeit","face":"markant, wettergegerbt","hair":"dunkelblond","eyes":"graugrün","voice":"ruhig, tief","posture":"aufrecht, aber unauffällig","typicalExpression":"zurückhaltend beobachtend","hands":"schwielig, kräftig","grooming":"einfach, aber gepflegt","clothing":"schlichte Arbeitskleidung eines Pächtersohns","distinguishingFeatures":"kleine Narbe am linken Handrücken","generalPresence":"unaufdringlich, aber bemerkbar ruhig"}', '{"characterId":"char_player_matthias","basePortrait":"asset://character/matthias/base","currentOutfit":"work_shirt","currentHairState":"neutral","currentAge":"22","currentCondition":"healthy","availableExpressions":["neutral"]}', '{"traits":["zurückhaltend","beobachtend","trockener Humor","verlässlich","stur"]}', '{"shortTerm":["die Ernte sichern"],"midTerm":["der Familie ein sichereres Auskommen verschaffen"],"longTerm":[],"currentWorries":["knappe Pacht"],"currentObligations":[],"currentPriorities":["Hof","Familie"],"plannedActions":[],"currentlyImportantPeople":["char_anne_hale","char_grace_hale"]}',
  '[]', '{}'
);
INSERT INTO characters (id, simulation_id, name, is_canon, is_player, location_id, appearance_json, visual_state_json, personality_json, goals_json, player_knowledge_json, gm_state_json) VALUES (
  'char_anne_hale', 'sim_default', 'Anne Hale', 0, 0, 'loc_player_farm',
  '{"height":"mittelgroß","build":"schlank, von harter Arbeit gezeichnet","face":"freundlich, müde Augen","hair":"graumeliert, zurückgebunden","eyes":"graugrün wie Matthias","voice":"warm, bestimmt","posture":"leicht gebeugt","typicalExpression":"sorgenvoll-liebevoll","hands":"rau von Hausarbeit","grooming":"einfach, ordentlich","clothing":"schlichtes Kleid, geflickt aber sauber","distinguishingFeatures":"—","generalPresence":"das ruhige Zentrum des Haushalts"}', '{"characterId":"char_anne_hale","basePortrait":"asset://character/anne/base","currentOutfit":"everyday_dress","currentHairState":"neutral","currentAge":"47","currentCondition":"healthy","availableExpressions":["neutral"]}', '{"traits":["fürsorglich","praktisch","zäh"]}', '{"shortTerm":["den Haushalt durch den Winter bringen"],"midTerm":[],"longTerm":["Grace gut verheiratet oder versorgt wissen"],"currentWorries":["Matthias arbeitet zu viel"],"currentObligations":[],"currentPriorities":["Familie"],"plannedActions":[],"currentlyImportantPeople":["char_player_matthias","char_grace_hale"]}',
  '[]', '{}'
);
INSERT INTO characters (id, simulation_id, name, is_canon, is_player, location_id, appearance_json, visual_state_json, personality_json, goals_json, player_knowledge_json, gm_state_json) VALUES (
  'char_grace_hale', 'sim_default', 'Grace Hale', 0, 0, 'loc_player_farm',
  '{"height":"klein","build":"schmal, noch jugendlich","face":"lebhaft","hair":"dunkelblond wie ihr Bruder","eyes":"graugrün","voice":"hell, schnell","posture":"quirlig","typicalExpression":"neugierig","hands":"—","grooming":"einfach","clothing":"einfaches Kleid","distinguishingFeatures":"—","generalPresence":"bringt Leben ins Haus"}', '{"characterId":"char_grace_hale","basePortrait":"asset://character/grace/base","currentOutfit":"everyday_dress","currentHairState":"neutral","currentAge":"16","currentCondition":"healthy","availableExpressions":["neutral"]}', '{"traits":["neugierig","lebhaft","ungeduldig"]}', '{"shortTerm":["mehr von der Welt jenseits des Hofes sehen"],"midTerm":[],"longTerm":[],"currentWorries":[],"currentObligations":["Mutter im Haushalt helfen"],"currentPriorities":[],"plannedActions":[],"currentlyImportantPeople":["char_player_matthias","char_anne_hale"]}',
  '[]', '{}'
);
INSERT INTO characters (id, simulation_id, name, is_canon, is_player, location_id, appearance_json, visual_state_json, personality_json, goals_json, player_knowledge_json, gm_state_json) VALUES (
  'char_thomas_hale', 'sim_default', 'Thomas Hale', 0, 0, NULL,
  '{"height":"groß","build":"kräftig","face":"wettergegerbt, Bruder von Matthias'' verstorbenem Vater","hair":"ergraut","eyes":"braun","voice":"laut, herzlich","posture":"aufrecht","typicalExpression":"joviale Zurückhaltung","hands":"schwielig","grooming":"einfach","clothing":"Händlerkleidung","distinguishingFeatures":"—","generalPresence":"entfernt, aber verlässlich"}', '{"characterId":"char_thomas_hale","basePortrait":"asset://character/thomas/base","currentOutfit":"travel_coat","currentHairState":"neutral","currentAge":"51","currentCondition":"healthy","availableExpressions":["neutral"]}', '{"traits":["herzlich","geschäftstüchtig"]}', '{"shortTerm":[],"midTerm":[],"longTerm":[],"currentWorries":[],"currentObligations":[],"currentPriorities":[],"plannedActions":[],"currentlyImportantPeople":["char_player_matthias"]}',
  '["Bruder des verstorbenen Vaters","Kornhändler in Bristol"]', '{}'
);

INSERT INTO relationships (simulation_id, from_id, to_id, type, dimensions_json, momentum, attention, public_stance, private_stance) VALUES (
  'sim_default', 'char_player_matthias', 'char_anne_hale', 'Mutter', '{"acquaintance":100,"liking":85,"trust":90,"respect":85,"familiarity":95,"sharedHumor":0,"emotionalCloseness":0,"intellectualConnection":0,"physicalAttraction":0,"aestheticAttraction":0,"romanticCuriosity":0,"romanticInterest":0,"romanticFeelings":0,"romanticTension":0,"sexualTension":0,"desireForCloseness":0,"loyalty":95,"protectiveness":80,"socialAcceptance":0,"willingnessToMarry":0,"distrust":0,"insecurity":0,"hurt":0,"anger":0,"jealousy":0,"rivalry":0,"fear":0,"dependency":0}', 'stable', 'high', 'respektvoller Sohn', 'liebevoll, beschützend'
);
INSERT INTO relationships (simulation_id, from_id, to_id, type, dimensions_json, momentum, attention, public_stance, private_stance) VALUES (
  'sim_default', 'char_player_matthias', 'char_grace_hale', 'Schwester', '{"acquaintance":100,"liking":80,"trust":75,"respect":60,"familiarity":90,"sharedHumor":55,"emotionalCloseness":0,"intellectualConnection":0,"physicalAttraction":0,"aestheticAttraction":0,"romanticCuriosity":0,"romanticInterest":0,"romanticFeelings":0,"romanticTension":0,"sexualTension":0,"desireForCloseness":0,"loyalty":90,"protectiveness":85,"socialAcceptance":0,"willingnessToMarry":0,"distrust":0,"insecurity":0,"hurt":0,"anger":0,"jealousy":0,"rivalry":0,"fear":0,"dependency":0}', 'stable', 'medium', 'beschützender großer Bruder', 'liebevoll genervt'
);
INSERT INTO relationships (simulation_id, from_id, to_id, type, dimensions_json, momentum, attention, public_stance, private_stance) VALUES (
  'sim_default', 'char_player_matthias', 'char_thomas_hale', 'Onkel', '{"acquaintance":70,"liking":65,"trust":60,"respect":65,"familiarity":40,"sharedHumor":0,"emotionalCloseness":0,"intellectualConnection":0,"physicalAttraction":0,"aestheticAttraction":0,"romanticCuriosity":0,"romanticInterest":0,"romanticFeelings":0,"romanticTension":0,"sexualTension":0,"desireForCloseness":0,"loyalty":55,"protectiveness":20,"socialAcceptance":0,"willingnessToMarry":0,"distrust":0,"insecurity":0,"hurt":0,"anger":0,"jealousy":0,"rivalry":0,"fear":0,"dependency":0}', 'slightly-positive', 'low', 'dankbarer Neffe', 'distanziert, aber respektvoll'
);

INSERT INTO locations (id, simulation_id, name, type, discovered, base_asset, map_x, map_y, travel_json) VALUES (
  'loc_player_farm', 'sim_default', 'Der Hale-Hof', 'farm', 1, 'asset://location/player_farm/base', 22, 78, NULL
);
INSERT INTO locations (id, simulation_id, name, type, discovered, base_asset, map_x, map_y, travel_json) VALUES (
  'loc_village_market', 'sim_default', 'Dorfmarkt', 'market', 1, 'asset://location/village_market/base', 34, 62, '{"distance":"knapp 2 Meilen","travelTime":"etwa eine halbe Stunde zu Fuß","transport":"zu Fuß oder mit dem Karren","cost":"keine"}'
);
INSERT INTO locations (id, simulation_id, name, type, discovered, base_asset, map_x, map_y, travel_json) VALUES (
  'loc_london', 'sim_default', 'London', 'city', 1, 'asset://location/london/base', 72, 30, '{"distance":"etwa 12 Meilen","travelTime":"zwei bis drei Stunden mit der Kutsche","transport":"Postkutsche oder eigenes Gespann","cost":"einige Shilling"}'
);
INSERT INTO locations (id, simulation_id, name, type, discovered, base_asset, map_x, map_y, travel_json) VALUES (
  'loc_aubrey_hall', 'sim_default', 'Aubrey Hall', 'estate', 0, 'asset://location/aubrey_hall/base', 82, 74, NULL
);

INSERT INTO memories (id, simulation_id, entity_ids_json, world_date, type, importance, fact, interpretation_json, status, reach, fading, tags_json) VALUES (
  'memory_1', 'sim_default', '["char_player_matthias","char_anne_hale","char_grace_hale"]', '1811', 'life-event', 'major', 'Matthias’ Vater starb nach kurzer Krankheit; seither trägt Matthias die Hauptverantwortung für den Hof.', '{}', 'fact', 'household', 'permanent', '["family","loss"]'
);
INSERT INTO memories (id, simulation_id, entity_ids_json, world_date, type, importance, fact, interpretation_json, status, reach, fading, tags_json) VALUES (
  'memory_2', 'sim_default', '["char_player_matthias","char_thomas_hale"]', '9. April 1813', 'letter', 'important', 'Onkel Thomas’ erster Brief seit langer Zeit traf ein — ein Zeichen, dass die Familie nicht vergessen ist.', '{}', 'fact', 'household', 'slow', '["family","letter"]'
);

INSERT INTO letters (id, simulation_id, sender_id, recipient_id, date_written, date_sent, date_arrived, content, status, known_by_json) VALUES (
  'letter_1', 'sim_default', 'char_thomas_hale', 'char_player_matthias', '3. April 1813', '3. April 1813', '9. April 1813', 'Mein lieber Matthias,

ich hoffe, dieser Brief findet Euch und Eure Mutter bei guter Gesundheit. Die Geschäfte hier in Bristol laufen gut, und ich habe an Deinen Vater gedacht, als der Weizenpreis diese Woche wieder anzog...', 'delivered', '["char_player_matthias","char_thomas_hale"]'
);

INSERT INTO chapters (id, simulation_id, number, title, summary, start_date) VALUES (
  'chapter_1', 'sim_default', 1, 'A Quiet Spring', 'Der Hof, die Familie und die ersten Nachrichten von der beginnenden London Season.', '1. April 1813'
);

INSERT INTO finance_transactions (id, simulation_id, date, description, amount) VALUES (
  'txn_1', 'sim_default', '2. April 1813', 'Saatgut', -3.5
);
INSERT INTO finance_transactions (id, simulation_id, date, description, amount) VALUES (
  'txn_2', 'sim_default', '5. April 1813', 'Marktverkauf — Eier', 1.2
);
INSERT INTO finance_transactions (id, simulation_id, date, description, amount) VALUES (
  'txn_3', 'sim_default', '9. April 1813', 'Reparatur Zaun', -0.8
);
INSERT INTO finance_transactions (id, simulation_id, date, description, amount) VALUES (
  'txn_4', 'sim_default', '11. April 1813', 'Pacht (Quartal)', -6
);

INSERT INTO world_events (id, simulation_id, category, title, description, date) VALUES (
  'event_1', 'sim_default', 'social', 'Die Season hat begonnen', 'Die ersten Kutschen mit jungen Damen und ihren Müttern sind in Richtung London aufgebrochen.', '10. April 1813'
);
INSERT INTO world_events (id, simulation_id, category, title, description, date) VALUES (
  'event_2', 'sim_default', 'local', 'Neuer Pächter am Nachbarhof', 'Die Braddocks haben den leerstehenden Hof im Westen übernommen.', '8. April 1813'
);
INSERT INTO world_events (id, simulation_id, category, title, description, date) VALUES (
  'event_3', 'sim_default', 'economic', 'Getreidepreise ziehen an', 'Auf dem Wochenmarkt wird über steigende Preise für Weizen gesprochen.', '11. April 1813'
);

INSERT INTO social_calendar (id, simulation_id, title, date, host, location, access) VALUES (
  'social_1', 'sim_default', 'Lady Danbury''s Evening', '20. April 1813', 'Lady Danbury', 'Danbury House, London', 'not-invited'
);
